version: "3.8"

services:

  db:
    image: postgres:13.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: kOjzgsF
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db:
